### ISSUE TITLE
Implement Python Black and Flake8 Pre commits

### ISSUE THREAD

**Issue by dangkv** [dangkv/iracing_garage#4]
## Goal
The objective of this issue is to create a CI (Continuous Integration) to force Python [Black](https://github.com/psf/black) and pep8 standards to our code base. Black is a python package that automatically for formats your python code. Flake8 is a package that highlights Python code that doesn't follow pep8 standards. This allows the code to be readable, maintainable, and efficient.

## Objective
- On commits, I want the automation pep8 and black to run
- I want a github action to validate if the code is up to standards before being implemented into production

## Steps

- [ ] install pre-commits
- [ ] install black and flake8 modele in pre-commits
- [ ] configure pre-commits rules
- [ ] configure black and flake8 rules

## Resources
- https://www.youtube.com/watch?v=XFyLzr5Ehf0
- https://black.readthedocs.io/en/stable/integrations/github_actions.html
- https://github.com/marketplace/actions/run-black-formatter

**Comment by dangkv** [comment]
@hmkamel 

Here is an example of `flake8` and `black` pre-commit config file.
- https://github.com/datacoves/dbt-coves/blob/main/.pre-commit-config.yaml
- https://github.com/datacoves/dbt-coves/blob/main/.flake8

**Comment by hmkamel** [comment]
ready to [pull changes from branch](https://github.com/dangkv/iracing_garage/pull/8) `[hmkamel-patch-apply-black&flake8]` to master. 

Review if needed.
