### ISSUE TITLE
Create a script to extract metadata on each iRacing endpoints and save it in a formatted markdown file

### ISSUE THREAD

**Issue by dangkv** [dangkv/iracing_garage#7]
## Objective:
Create a script that extracts the iRacing endpoint parameters and save it in a formatted markdown file.

You can find all the metadata in this json file: [api.json](https://github.com/dangkv/iracing_garage/files/15229398/api.json)

### Acceptance Criteria:
- [ ] One md file for all the methods and arguments
- [ ] The python script itself does not need to be In the package, just the formatted md files
- [ ] Save the file under ./docs as `methods.md`

---

The format of the markdown:

``` markdown
### car.assets()

image paths are relative to https://images-static.iracing.com/

link:`https://members-ng.iracing.com/data/car/assets`

---

### car.get()

link: `https://members-ng.iracing.com/data/car/get`

---

### carclass.get()

link: `https://members-ng.iracing.com/data/carclass/get`

---

### hosted.combined_sessions()

Sessions that can be joined as a driver or spectator, and also includes non-league pending sessions for the user.

| Argument   | Data Type | Description                                                      | Required |
|------------|-----------|------------------------------------------------------------------|----------|
| package_id | number    | If set, return only sessions using this car or track package ID. | False    |

link: `https://members-ng.iracing.com/data/hosted/combined_sessions`
```

**Comment by dangkv** [comment]
Some useful tips:

- use `.get()` to extract keys from a dictionary
- Some notes can be lists
- you might need to look for a md library to simplify writing down markdown formatted files and build md tables
- This script does not need to follow best practices since its a one time used script

**Comment by dangkv** [comment]
## API Reference

#### car.assets()

```http
  GET https://members-ng.iracing.com/data/car/assets
```

#### hosted.combined_sessions()

Note on this API endpoints, insert here

```http
https://members-ng.iracing.com/data/hosted/combined_sessions
```

| Parameter    | Type     | Description                                                      | Required |
|--------------|----------|------------------------------------------------------------------|----------|
| `package_id` | `number` | If set, return only sessions using this car or track package ID. | False    |

**Comment by hmkamel** [comment]
[Pull request](https://github.com/dangkv/iracing_garage/pull/9) to merge methods.md file to repo source

You can check out a the code + MD file [here](https://gist.github.com/hmkamel/7731cd1c626b0c4500d89e1991695b63)

**Comment by dangkv** [comment]
Key changes:

- Add H2 subtitle for each apigroup
- Create `---` dividers after each api group instead of each endpoints
- Endpoints with no notes, add a `No description`
- Wrap the API link with http block code

# Example
---


# iRacing Garage

A brief description of what this project does and who it's for - TO BE ADDED

## Car
### car.assets()

Image paths are relative to https://images-static.iracing.com/


```http
https://members-ng.iracing.com/data/car/assets
```


### car.get()

No descrpition.

```http
https://members-ng.iracing.com/data/car/get
```

---

## Carclass

### carclass.get()

No descrpition.

```http
https://members-ng.iracing.com/data/carclass/get
```

---

## Constants

### constants.categories()

Constant; returned directly as an array of objects


```http
https://members-ng.iracing.com/data/constants/categories
```

### constants.divisions()

Constant; returned directly as an array of objects


```http
https://members-ng.iracing.com/data/constants/divisions
```


### constants.event_types()

Constant; returned directly as an array of objects


```http
https://members-ng.iracing.com/data/constants/event_types
```

---

## Hosted

### hosted.combined_sessions()

Sessions that can be joined as a driver or spectator, and also includes non-league pending sessions for the user.

| Parameter | Type | Description | Required |
|:---------|:----:|:------------|:--------:|
| `package_id` | `number` | If set, return only sessions using this car or track package ID. | False |

```http
https://members-ng.iracing.com/data/hosted/combined_sessions
```

---

**Comment by hmkamel** [comment]
Review the changed made [here ](https://github.com/dangkv/iracing_garage/pull/12) and if good, approve pull.
Also added the python script that converted the JSON file to Markdown.

@dangkv
